version: '3.7'

services:
  vault:
    image: vault
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8200/ui/vault/auth" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
